"""Add user-order relationship

Revision ID: 0ada6921b672
Revises: 02a55e62d3dd
Create Date: 2025-09-24 09:16:28.626424

"""

from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "0ada6921b672"
down_revision: Union[str, Sequence[str], None] = "02a55e62d3dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
